const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={token:new URLSearchParams(location.search).get('token')||localStorage.getItem('rumonium_token')||'',socket:null,latency:0};
if(new URLSearchParams(location.search).get('token'))localStorage.setItem('rumonium_token',state.token);
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(state.token?{'X-Control-Token':state.token}:{})};const r=await fetch(url,opt);if(r.status===401){toast('Control token required','bad');throw Error('Unauthorized')}const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}}if(!r.ok)throw Error(d.message||`HTTP ${r.status}`);return d}
const post=(u,d={})=>api(u,{method:'POST',body:JSON.stringify(d)});
function toast(m,c=''){const e=document.createElement('div');e.className='toast '+c;e.textContent=m;$('#toast-stack').append(e);setTimeout(()=>e.remove(),3000)}
function uptime(s){s=Math.floor(s);const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);return d?`${d}d ${h}h ${m}m`:`${h}h ${m}m`}
function setStatus(s){const t=s==='online'?'ONLINE':s==='connecting'?'CONNECTING':'OFFLINE';['side-status','m-status','bot-state','hero-node'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=t});const col=s==='online'?'var(--good)':s==='connecting'?'var(--warn)':'var(--bad)';$('#side-dot').style.background=col;$('#m-status-signal').style.background=col;$('#m-status-sub').textContent=s==='online'?'Connected to Minecraft':'Awaiting connection';$('#bot-detail').textContent=s==='online'?'The client is connected and operational.':s==='connecting'?'Negotiating connection...':'The client is not connected.'}
function render(d){const t=d.telemetry,b=d.bot;setStatus(b.ready?'online':b.connected?'connecting':'offline');$('#m-memory').textContent=t.memoryMb;$('#m-queue').textContent=t.apiQueue;$('#m-commands').textContent=t.commands;$('#hero-uptime').textContent='UPTIME '+uptime(t.uptimeMs/1000);$('#health-api').textContent=t.apiQueue<3?'CLEAR':'BUSY';$('#health-cache').textContent=t.cacheSize+' ENTRIES';$('#health-bot').textContent=b.ready?'NOMINAL':'ATTENTION';$('#health-urchin').textContent=d.settings?.autoReconnect?'ENABLED':'STANDBY';$('#feed').innerHTML=(d.recent||[]).slice(0,25).map(x=>`<div class="feed-item"><time>${esc(x.time||'--')}</time><b>${esc((x.type||'EVENT').toUpperCase())}</b><span>${esc(x.message||x.msg||'')}</span></div>`).join('')||'<div class="feed-item"><time>--:--</time><b>SYSTEM</b><span>Waiting for telemetry...</span></div>';const max=Math.max(1,...(d.topCommands||[]).map(x=>x.count));$('#top-commands').innerHTML=(d.topCommands||[]).map(x=>`<div class="bar"><span>${esc(x.command)}</span><i style="width:${Math.max(4,x.count/max*100)}%"></i><b>${x.count}</b></div>`).join('')||'<span>No command activity.</span>';$('#top-users').innerHTML=(d.topUsers||[]).map((x,i)=>`<div class="rank"><span><b>${String(i+1).padStart(2,'0')}</b> ${esc(x.username)}</span><b>${x.count}</b></div>`).join('')||'<div class="rank">No operator activity.</div>';syncSettings(d.settings);renderTracking(d)}
function syncSettings(s){if(!s)return;$('#s-auto').checked=!!s.autoReconnect;$('#s-welcome').checked=!!s.welcomeMessages;$('#s-cooldown').value=s.commandCooldown??45;$('#s-delay').value=s.performance?.messageDelay??300;$('#s-reconnect').value=s.performance?.autoReconnectDelay??15000}
async function load(){const t=performance.now();try{const d=await api('/api/dashboard');state.latency=Math.round(performance.now()-t);$('#latency').textContent=state.latency+' ms';render(d);loadAI();loadPermissions()}catch(e){}}
async function loadAI(){try{$('#ai-prompt').value=(await api('/api/gpt-prompt')).prompt||''}catch{}}
async function saveSettings(){const data={autoReconnect:$('#s-auto').checked,welcomeMessages:$('#s-welcome').checked,commandCooldown:+$('#s-cooldown').value,performance:{messageDelay:+$('#s-delay').value,autoReconnectDelay:+$('#s-reconnect').value}};$('#settings-state').textContent='SAVING...';try{await post('/api/settings',data);$('#settings-state').textContent='LIVE';toast('Runtime settings applied')}catch(e){$('#settings-state').textContent='ERROR';toast(e.message,'bad')}}
function term(m,c=''){const e=document.createElement('div');e.className='term-line '+c;e.innerHTML=`<b>[${new Date().toLocaleTimeString()}]</b> ${esc(m)}`;$('#terminal').append(e);$('#terminal').scrollTop=1e9}
async function action(p){try{const r=await post(p);toast(r.message||'Action accepted');term(r.message||p)}catch(e){toast(e.message,'bad');term(e.message,'error')}}
async function lookup(){const u=$('#lookup').value.trim();if(!u)return;$('#dossier').classList.remove('hidden');$('#d-name').textContent=u;$('#d-meta').textContent='Analyzing live signals...';try{const d=await api('/api/player/lookup?username='+encodeURIComponent(u)),s=d.stats||{};$('#d-star').textContent=s.star??'—';$('#d-fkdr').textContent=s.fkdr??'—';$('#d-wl').textContent=s.wl??'—';$('#d-finals').textContent=(s.finals??0).toLocaleString();$('#d-wins').textContent=(s.wins??0).toLocaleString();$('#d-rank').textContent=d.gexp?.rank??'—';$('#d-gexp').textContent=d.gexp?.weeklyGexp?.toLocaleString()??'—';$('#d-members').textContent=d.gexp?.totalMembers??'—';const flag=!!d.localBlacklist;$('#d-blacklist').textContent=flag?'FLAGGED':'CLEAR';$('#d-blacklist').style.color=flag?'var(--bad)':'var(--good)';$('#d-risk').textContent=flag?'FLAGGED':'NOMINAL';$('#d-risk').style.color=flag?'var(--bad)':'var(--good)';$('#d-meta').textContent=[d.statsError,d.gexpError].filter(Boolean).join(' · ')||'Live analysis complete';$('#d-urchin').textContent=typeof d.urchin==='string'?d.urchin:JSON.stringify(d.urchin,null,2);$('#mc-avatar').textContent=u[0].toUpperCase()}catch(e){$('#d-meta').textContent=e.message;toast(e.message,'bad')}}
function renderTracking(d){const f=d.fkdrTracking||[],a=d.activity||[];$('#fkdr-count').textContent=f.length;$('#activity-count').textContent=a.length;$('#fkdr-list').innerHTML=f.map(x=>`<div class="table-row"><b>${esc(x.username)}</b><span>${esc(x.progress?.status||'TRACKING')}</span><b>${x.progress?.current??'—'}</b></div>`).join('')||'<div class="table-row"><span>No FKDR tracking.</span></div>';$('#activity-list').innerHTML=a.map(x=>`<div class="table-row"><b>${esc(x.username)}</b><span>${esc(x.detection?.status||'ACTIVE')}</span><b>${x.snapshots?.length??0}</b></div>`).join('')||'<div class="table-row"><span>No activity tracking.</span></div>'}
async function perms(){try{const d=await api('/api/permissions');$('#perm-list').innerHTML=d.permissions.map(p=>`<div class="perm"><b>${esc(p.username)}</b><span>${esc((p.allowedCommands||[]).join(', ')||'ALL')}</span><span>${esc((p.bannedCommands||[]).join(', ')||'NONE')}</span><button data-remove="${esc(p.username)}">RESET</button></div>`).join('')||'<div class="perm">No custom access rules.</div>'}catch{}}
const cmds=[['Overview','overview'],['Bot Control','bot'],['Player Intel','intelligence'],['Tracking','tracking'],['Access','access'],['AI Core','ai'],['System','system'],['Start bot','/api/bot/start'],['Reconnect bot','/api/bot/reconnect'],['Disconnect bot','/api/bot/disconnect'],['Clear cache','/api/cache/clear']];
function page(id){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$('#page-title').textContent=id.toUpperCase()}
function openPalette(){const m=$('#palette'),i=$('#palette-input'),list=$('#palette-items');m.classList.add('open');i.value='';i.focus();const draw=q=>list.innerHTML=cmds.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).map((x,n)=>`<button class="palette-item ${n?'':'active'}" data-cmd="${x[1]}"><b>${esc(x[0])}</b><span>${x[1].startsWith('/')?'Execute':'Navigate'}</span></button>`).join('');draw('');i.oninput=()=>draw(i.value)}
function closePalette(){$('#palette').classList.remove('open')}
$$('.nav').forEach(x=>x.onclick=()=>page(x.dataset.page));$('#open-palette').onclick=openPalette;$('#palette').onclick=e=>{if(e.target.id==='palette')return closePalette();const b=e.target.closest('[data-cmd]');if(!b)return;b.dataset.cmd.startsWith('/')?action(b.dataset.cmd):page(b.dataset.cmd);closePalette()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape')closePalette()});
$('#refresh').onclick=load;$('#bot-start').onclick=()=>action('/api/bot/start');$('#bot-reconnect').onclick=()=>action('/api/bot/reconnect');$('#bot-stop').onclick=()=>action('/api/bot/disconnect');['s-auto','s-welcome','s-cooldown','s-delay','s-reconnect'].forEach(id=>$('#'+id).onchange=saveSettings);$('#chat-form').onsubmit=async e=>{e.preventDefault();const i=$('#chat-input'),m=i.value.trim();if(!m)return;try{await post('/chat',{message:m});term('SENT '+m);i.value=''}catch(e){toast(e.message,'bad')}};$('#lookup-form').onsubmit=e=>{e.preventDefault();lookup()};$('#perm-save').onclick=async()=>{const u=$('#perm-user').value.trim();if(!u)return;try{await post('/api/permissions/set',{username:u,allowedCommands:$('#perm-allow').value.split(',').map(x=>x.trim()).filter(Boolean),bannedCommands:$('#perm-ban').value.split(',').map(x=>x.trim()).filter(Boolean)});toast('Access policy updated');['perm-user','perm-allow','perm-ban'].forEach(id=>$('#'+id).value='');perms()}catch(e){toast(e.message,'bad')}};$('#perm-list').onclick=async e=>{const b=e.target.closest('[data-remove]');if(b){await post('/api/permissions/remove',{username:b.dataset.remove});toast('Access reset');perms()}};$('#ai-save').onclick=async()=>{try{await post('/api/gpt-prompt',{prompt:$('#ai-prompt').value});$('#ai-state').textContent='DEPLOYED';toast('AI directive deployed')}catch(e){toast(e.message,'bad')}};$('#clear-cache').onclick=()=>action('/api/cache/clear');
async function system(){try{const d=await api('/api/system-info');$('#sys-node').textContent=d.nodeVersion;$('#sys-platform').textContent=d.platform;$('#sys-pid').textContent=d.pid;$('#sys-rss').textContent=d.rss+' MB';$('#sys-up').textContent=uptime(d.uptime)}catch{}}
function socket(){try{state.socket=io({auth:{token:state.token}});state.socket.on('connect',()=>term('CONTROL SOCKET ESTABLISHED'));state.socket.on('connect_error',e=>toast(e.message,'bad'));state.socket.on('bot-status',s=>{setStatus(s);term('BOT STATUS '+s.toUpperCase())});state.socket.on('bot-log',x=>{term(x.msg||x.message||'event',x.type==='error'?'error':'')});state.socket.on('telemetry',x=>{$('#m-memory').textContent=x.memory;$('#m-queue').textContent=x.queue;$('#m-commands').textContent=x.commands});state.socket.on('control-state',x=>setStatus(x.botStatus))}catch(e){console.warn(e)}}
$('#export-backup').onclick=async()=>{try{const r=await fetch('/api/export/all',{headers:state.token?{'X-Control-Token':state.token}:{}});if(!r.ok)throw Error('Export failed');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rumonium-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}catch(e){toast(e.message,'bad')}};load();system();socket();setInterval(load,15000);
